[exception_details.py]
  expected: TIMEOUT
