[connect.py]
  [test_websocket_url_connect[capabilities0\]]
    expected: ERROR
