[exception_details_await_promise.py]
  [test_exception_details_await_promise[([1, 2\][Symbol.iterator\]())-expected28\]]
    expected: FAIL
