[exception_details_await_promise.py]
  [test_exception_details_await_promise[(new Set([1,2\]))[Symbol.iterator\]()-expected30\]]
    expected: FAIL

  [test_exception_details_await_promise[(new Map([[1,2\]\]))[Symbol.iterator\]()-expected31\]]
    expected: FAIL
