[exception_details.py]
  [test_exception_details[([1, 2\][Symbol.iterator\]())-expected28\]]
    expected: FAIL
